/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multex.apresentacao.grafica.telas;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.util.Duration.seconds;
import javax.swing.DefaultListModel;
import javax.swing.Timer;
import multex.apresentacao.grafica.Reminder;

/**
 *
 * @author rudnik
 */
public class Principal extends javax.swing.JFrame {
    private boolean memoria;
    private DefaultListModel lista;
    private DefaultListModel listaEspera;
    private int numeroProcesso;
    private Timer t;
    private boolean travaLock;
     /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        memoria = false;
        travaLock = false;
        numeroProcesso = 0;
        lista = new DefaultListModel();
        listaEspera = new DefaultListModel();
        lstProcesso.setModel(lista);
        lstEspera.setModel(listaEspera);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaCritica = new javax.swing.JLabel();
        btnProcesso1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProcesso = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEspera = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaCritica.setText("AREA CRITICA");

        btnProcesso1.setText("Adicionar Processo");
        btnProcesso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesso1ActionPerformed(evt);
            }
        });

        lstProcesso.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstProcesso);

        lstEspera.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstEspera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(areaCritica, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(areaCritica, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesso1ActionPerformed
        int n = this.numeroProcesso;
        numeroProcesso ++;
        ActionListener suaActionListener = new ActionListener() {  
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {             
            lista.addElement("Processo "+n+" Finalizou...");
            memoria = false;
            areaCritica.setText("Disponível");
            areaCritica.setForeground(Color.green);
            t.stop();
            pegaProximo();
            
        }};
        if(memoria || !listaEspera.isEmpty()){
            listaEspera.addElement("Processo "+(n)+" Aguardando...");
            return;
        }
        
        t = new Timer(5000, suaActionListener);
        //t = new Timer((int)(Math.random()*1000), suaActionListener);
        lista.addElement("Processo "+n+" Consumindo...");
        memoria = true;
        areaCritica.setText("Ocupado");
        areaCritica.setForeground(Color.red);
        t.start();
        
        
        
    }//GEN-LAST:event_btnProcesso1ActionPerformed

    public void pegaProximo(){
        if (listaEspera.isEmpty())
            return;
        String s = listaEspera.firstElement().toString().replaceAll("Aguardando...", "Consumindo...");
        lista.addElement(s);
        listaEspera.remove(0);

        
        ActionListener suaActionListener = new ActionListener() {  
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {             
            lista.addElement(s.replaceAll("Consumindo...", "Finalizou..."));
            memoria = false;
            areaCritica.setText("Disponível");
            areaCritica.setForeground(Color.green);
            t.stop();
            pegaProximo();
            
        }};
        
        t = new Timer(5000, suaActionListener);
        //t = new Timer((int)(Math.random()*1000), suaActionListener);
        memoria = true;
        areaCritica.setText("Ocupado");
        areaCritica.setForeground(Color.red);
        t.start();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaCritica;
    private javax.swing.JButton btnProcesso1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstEspera;
    private javax.swing.JList<String> lstProcesso;
    // End of variables declaration//GEN-END:variables
}
